export const CommonTexts = {
  en: {
    'button.confirm': 'Confirm',
    'button.continue': 'Continue',
    'button.cancel': 'Cancel',
    'button.remove': 'Remove',
    'button.save': 'Save',
    'button.clone': 'Clone',
    'button.apply': 'Apply',
    'button.search': 'Search',
    'button.edit': 'Edit',
    'button.open': 'Open',
    'button.close': 'Close',
    'button.add': 'Add',
    'button.filter': 'Filter',
    'button.clear': 'Clear',
    'button.play': 'Play',
    'button.pause': 'Pause',
    'label.public': 'Public',
    'label.private': 'Private',
    'label.notavailable': 'N/A',
    'generic.boolean.true': 'Yes',
    'generic.boolean.false': 'No',
    'select.empty': 'Select',
    'pagination.label.showing': '',
    'pagination.label.results': 'results per page',
    'pagination.label.total': 'Total',
    'generic.loading': 'Loading...',
    'generic.placeholder': 'Type here',
    'generic.placeholder.comma.separated': 'Type here separated by commas',
    'generic.placeholder.select': 'Select one here',
    'validation.required': 'Required field.',
    'placeholder.check': 'click to choose',
    'placeholder.input': 'click to add',
    'update.success': 'saved!',
    'table.label.rows-page': 'Items per page',
    'table.label.pages': 'of {{value}} pages',
    'table.label.items': '{{first}} - {{last}} of {{total}} items',
    'tooltip.copy': 'Copy',
    'tooltip.copied': 'Copied!',
  },
  'pt-BR': {
    'button.confirm': 'Confirmar',
    'button.continue': 'Continuar',
    'button.cancel': 'Cancelar',
    'button.remove': 'Remover',
    'button.save': 'Salvar',
    'button.clone': 'Clonar',
    'button.apply': 'Aplicar',
    'button.search': 'Buscar',
    'button.edit': 'Editar',
    'button.open': 'Abrir',
    'button.add': 'Adicionar',
    'button.close': 'Fechar',
    'button.filter': 'Filtrar',
    'button.clear': 'Limpar',
    'button.play': 'Reproduzir',
    'button.pause': 'Pausar',
    'label.public': 'Público',
    'label.private': 'Privado',
    'label.notavailable': 'N/A',
    'generic.boolean.true': 'Sim',
    'generic.boolean.false': 'Não',
    'select.empty': 'Selecionar',
    'pagination.label.showing': 'Exibindo',
    'pagination.label.results': 'resultados por página',
    'pagination.label.total': 'Total',
    'generic.loading': 'Carregando...',
    'generic.placeholder': 'Digite aqui',
    'generic.placeholder.select': 'Selecione um aqui',
    'generic.placeholder.comma.separated': 'Digite aqui separado por vírgulas',
    'validation.required': 'Campo obrigatório.',
    'placeholder.check': 'clique para selecionar',
    'placeholder.input': 'clique para adicionar',
    'update.success': 'salvo!',
    'table.label.rows-page': 'Itens por página',
    'table.label.pages': 'de {{value}} páginas',
    'table.label.items': '{{first}} - {{last}} de {{total}} itens',
    'tooltip.copy': 'Copiar',
    'tooltip.copied': 'Copiado!',
  },
  it: {
    'button.confirm': 'Conferma',
    'button.continue': 'Continua',
    'button.cancel': 'Annulla',
    'button.remove': 'Rimuovi',
    'button.save': 'Salva',
    'button.clone': 'Clona',
    'button.search': 'Cerca',
    'button.edit': 'Modifica',
    'button.open': 'Apri',
    'button.apply': 'Applica',
    'button.add': 'Aggiungi',
    'button.close': 'Chiudi',
    'button.filter': 'Filtra',
    'button.clear': 'Pulisci',
    'button.play': 'Riproduci',
    'button.pause': 'Pausa',
    'label.public': 'Pubblico',
    'label.private': 'Privato',
    'label.notavailable': 'N/A',
    'generic.boolean.true': 'Sì',
    'generic.boolean.false': 'No',
    'select.empty': 'Seleziona',
    'pagination.label.showing': 'Mostrando',
    'pagination.label.results': 'risultati per pagina',
    'pagination.label.total': 'Totale',
    'generic.loading': 'Caricamento...',
    'generic.placeholder': 'Scrivi qui',
    'generic.placeholder.select': 'Seleziona uno qui',
    'generic.placeholder.comma.separated': 'Scrivi qui separato per virgole',
    'validation.required': 'Campo obbligatorio.',
    'placeholder.check': 'clicca per scegliere',
    'placeholder.input': 'clicca per aggiungere',
    'update.success': 'salvato!',
    'table.label.rows-page': 'Elementi per pagina',
    'table.label.pages': 'di {{value}} pagine',
    'table.label.items': '{{first}} - {{last}} di {{total}} elementi',
    'tooltip.copy': 'Copia',
    'tooltip.copied': 'Copiato!',
  },
};
