export const TreeTexts = {
  en: {
    'button.expand.tree': 'Expand tree',
    'button.recenter.tree': 'Recenter tree',
    'button.download.tree': 'Download tree as image',
    'button.download.penn': 'Download in Penn Tree format',
    'button.info': 'Display translations and glosses',
    'placeholder.sentence.notparsed': 'This sentence has not been parsed.',
    'date.parsed': 'Parsing executed at:',
    'button.search': 'Search',
    'label.syntactic.category': 'Syntactic Category',
    'label.pos.tag': 'POS Tag',
    'label.empty.category': 'Empty Category',
    'label.word.value': 'Word',
  },
  'pt-BR': {
    'button.expand.tree': 'Expandir árvore',
    'button.recenter.tree': 'Recentralizar árvore',
    'button.download.tree': 'Baixar árvore como imagem',
    'button.download.penn': 'Baixar no formato Penn Tree',
    'button.info': 'Mostrar traduções e glosas',
    'placeholder.sentence.notparsed':
      'O parser não foi realizado nesta sentença.',
    'date.parsed': 'Parser executado às:',
    'button.search': 'Buscar',
    'label.syntactic.category': 'Categoria Sintática',
    'label.pos.tag': 'Etiqueta POS',
    'label.empty.category': 'Categoria Vazia',
    'label.word.value': 'Palavra',
  },
  it: {
    'button.expand.tree': 'Espandi albero',
    'button.recenter.tree': 'Ricentra albero',
    'button.download.tree': 'Scarica albero come immagine',
    'button.download.penn': 'Scarica in formato Penn Tree',
    'button.info': 'Visualizza traduzioni e glosse',
    'date.parsed': 'Parser eseguito alle:',
    'button.search': 'Cerca',
    'label.syntactic.category': 'Categoria Sintattica',
    'label.pos.tag': 'Etichetta POS',
    'label.empty.category': 'Categoria Vuota',
    'label.word.value': 'Parola',
  },
};
